package main

const TOKEN_IDENTIFIER = "TOKEN_IDENTIFIER"
const TOKEN_SYMBOL = "TOKEN_SYMBOL"
const TOKEN_NUMBER = "TOKEN_NUMBER"
const TOKEN_STRING = "TOKEN_STRING"

const AST_ROOT = "AST_ROOT"
const AST_NUMBER = "AST_NUMBER"
const AST_STRING = "AST_STRING"
const AST_BOOLEAN = "AST_BOOLEAN"
const AST_NULL = "AST_NULL"
const AST_IF_CONDITION = "AST_IF_CONDITION"
const AST_VAR_DECLARATION = "AST_VAR_DECLARATION"
const AST_VAR_REFERENCE = "AST_VAR_REFERENCE"
const AST_OPERATION = "AST_OPERATION"
const AST_FN_DECLARATION = "AST_FN_DECLARATION"
const AST_FN_CALL = "AST_FN_CALL"
